name: New version check
on:
  workflow_dispatch:
  schedule:
  - cron: 0 16 * * 5
  push:
    branches:
      - master

jobs:
  check:
    name: Check new version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Check new version
        shell: bash
        run: |
          ./update.sh

      - name: Commit and push
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "actions-user@users.noreply.github.com"
          git add Makefile
          git diff-index --cached --quiet HEAD Makefile \
          || (git commit -m "update to $(sed -En 's|^\s*PKG_VERSION\s*:=(.*)|\1|p' Makefile)" && git push)
